spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/boot
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: /Users/Kodongyoung/goodCasting
      max-request-size: 100MB
      max-file-size: 100MB
  security:
    jwt:
      secret: secret-value
  mail:
    host: smtp.gmail.com
    port: 587
    username: goodcastingofficial@gmail.com
    password: goodc1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
shop:
  goodcast:
    upload:
      path: /usr/local/goodCasting
UserController:
  signup: Create user and returns ins JWT token
  signin: Authenticaties user and returns ins JWT token
