spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/boot
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: secret-value

  mail:
    host: smtp.gmail.com
    port: 587
    username: goodcastingofficial@gmail.com
    password: goodc1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
